name: Run "Model" in a Docker container
on: workflow_dispatch
jobs:
  run-model:
    runs-on: ubuntu-latest
    env: 
       DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
       DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Build Docker image
      run: docker build -t vamsi1997docker/model:latest .
    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}
    - name: Push to docker hub :latest
      uses: actions-hub/docker@master
      with:
       args: push ${{ secrets.DOCKERHUB_USERNAME }}/my-image:latest
    - name: Run Python script in Docker container
      run: |
        docker login --username ${{ env.DOCKER_USERNAME }} --password ${{ env.DOCKER_PASSWORD }}
        docker run -p 8080:80 --name python ${{ secrets.DOCKERHUB_USERNAME }}/model:latest
